version: "3.9"

services:
  web:
    image: richuxd/online-art-gallery:latest
    container_name: django_app
    command: gunicorn onlineartgallery.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env 

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env   
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
