apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "securepassword"
  DJANGO_SECRET_KEY: "django-insecure-4fryt%12kg-x#u-#8*xxkse2$d-06$=2i(iw$n!g6b!6wln9&j"
  DJANGO_DEBUG: "1"

