apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-webapp
  template:
    metadata:
      labels:
        app: django-webapp
    spec:
      containers:
        - name: django-webapp
          image: richuxd/online-art-gallery:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_PORT
            - name : DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DJANGO_SECRET_KEY
            - name : DJANGO_DEBUG
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DJANGO_DEBUG

---
apiVersion: v1
kind: Service
metadata:
  name: django-webapp
spec:
  type: NodePort 
  selector:
    app: django-webapp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

